SET IDENTITY_INSERT [dbo].[Games] ON
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (1, N'Mass Effect: Andromeda is an action role-playing game in which the player takes control of either Scott or Sara Ryder from a third-person perspective.', N'https://upload.wikimedia.org/wikipedia/en/0/07/Mass_Effect_Andromeda_cover.jpeg', CAST(60.00 AS Decimal(18, 2)), N'2017-03-01 00:00:00', 62.5, N'MASS EFFECT ANDROMEDA', N'PRCEK2eYAVs')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (2, N'The S.T.A.L.K.E.R. games take place within "The Zone", an alternate history version of the Chernobyl Exclusion Zone', N'https://upload.wikimedia.org/wikipedia/en/e/ee/S.T.A.L.K.E.R_series_logo.jpg', CAST(52.00 AS Decimal(18, 2)), N'2012-12-30 00:00:00', 12, N'STALKER', N'xTq4ibgVof8')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (3, N'Counter-Strike (CS) is a series of multiplayer first-person shooter video games, in which teams of terrorists and counter-terrorists battle to, respectively, perpetrate an act of terror (bombing, hostage-taking) and prevent it (bomb defusal, hostage rescue).', N'https://upload.wikimedia.org/wikipedia/en/6/67/Counter-Strike_Box.jpg', CAST(42.00 AS Decimal(18, 2)), N'2000-09-21 00:00:00', 8, N'COUNTER-STRIKE', N'x1s2IVGkw5U')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (4, N'Assassin''s Creed is a franchise centered on an action-adventure video game series developed by Ubisoft. It depicts a centuries-old struggle pitting the Assassins, who fight for peace and free will, against the Templars, who believe peace comes through control of humanity.', N'https://upload.wikimedia.org/wikipedia/en/2/2a/Assassin%27s_Creed_Logo.svg', CAST(82.00 AS Decimal(18, 2)), N'2015-09-10 00:00:00', 34, N'ASSASSIN''S CREED', N'gfJVoF5ko1Y')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (5, N'Mass Effect: Andromeda is an action role-playing game in which the player takes control of either Scott or Sara Ryder from a third-person perspective.', N'https://upload.wikimedia.org/wikipedia/en/0/07/Mass_Effect_Andromeda_cover.jpeg', CAST(60.00 AS Decimal(18, 2)), N'2017-03-01 00:00:00', 62.5, N'MASS EFFECT ANDROMEDA', N'PRCEK2eYAVs')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (6, N'The S.T.A.L.K.E.R. games take place within "The Zone", an alternate history version of the Chernobyl Exclusion Zone', N'https://upload.wikimedia.org/wikipedia/en/e/ee/S.T.A.L.K.E.R_series_logo.jpg', CAST(52.00 AS Decimal(18, 2)), N'2012-12-30 00:00:00', 12, N'STALKER', N'xTq4ibgVof8')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (7, N'Counter-Strike (CS) is a series of multiplayer first-person shooter video games, in which teams of terrorists and counter-terrorists battle to, respectively, perpetrate an act of terror (bombing, hostage-taking) and prevent it (bomb defusal, hostage rescue).', N'https://upload.wikimedia.org/wikipedia/en/6/67/Counter-Strike_Box.jpg', CAST(42.00 AS Decimal(18, 2)), N'2000-09-21 00:00:00', 8, N'COUNTER-STRIKE', N'x1s2IVGkw5U')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (8, N'Assassin''s Creed is a franchise centered on an action-adventure video game series developed by Ubisoft. It depicts a centuries-old struggle pitting the Assassins, who fight for peace and free will, against the Templars, who believe peace comes through control of humanity.', N'https://upload.wikimedia.org/wikipedia/en/2/2a/Assassin%27s_Creed_Logo.svg', CAST(82.00 AS Decimal(18, 2)), N'2015-09-10 00:00:00', 34, N'ASSASSIN''S CREED', N'gfJVoF5ko1Y')
INSERT INTO [dbo].[Games] ([Id], [Description], [Image], [Price], [ReleaseDate], [Size], [Title], [VideoId]) VALUES (9, N'Tzar: The Burden of the Crown is a real-time strategy game for the PC published by Take-Two Interactive and developed by the Bulgarian game developer company Haemimont Games. It was released March 31, 2000 in the West. The game was met with moderate success; however, it got mild recognition and audience when it was published as a demo in several gaming magazines', N'https://upload.wikimedia.org/wikipedia/en/b/b7/Tzarburdenofthecrownbox.jpg', CAST(35.00 AS Decimal(18, 2)), N'1998-05-12 00:00:00', 17, N'TZAR: THE BURDEN OF THE CROWN', N'lPr8oA_B_3c')
SET IDENTITY_INSERT [dbo].[Games] OFF
